#ifndef SDLGPU_FORGE_GPU_LESSONS_H
#define SDLGPU_FORGE_GPU_LESSONS_H

#include "forge_gpu_internal.h"

bool ForgeGpuCreateLesson(ForgeGpuDemo *demo, int lesson_index);
void ForgeGpuDestroyLesson(ForgeGpuDemo *demo);

bool ForgeGpuCreateLesson01(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson02(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson02(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson03(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson03(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson04(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson04(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson05(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson05(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson05(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson05(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson05Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson05Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson05(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson06(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson06(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson07(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson07(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson08(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson08(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDestroyLesson08(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson09(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson09(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson10(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson10(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson11(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson11(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson11(ForgeGpuDemo *demo);
void ForgeGpuExportLesson11Metrics(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson12(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson12(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson13(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson13(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDestroyLesson13(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson14(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson14(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDestroyLesson14(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson15(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson15(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson15(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson15(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson15(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson16(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson16(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDestroyLesson16(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson17(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson17(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson17(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson17(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson17Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuDestroyLesson17(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson18(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson18(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
bool ForgeGpuCreateLesson19(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson19(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDestroyLesson19(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson20(ForgeGpuDemo *demo);
void ForgeGpuRenderLesson20(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson20(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson20(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson20Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuDestroyLesson20(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson21(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson21(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson21(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson21(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson21Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson21Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson21(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson22(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson22(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson22(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson22(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson22Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson22Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson22(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson23(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson23(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson23(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson23(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson23Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson23Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson23(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson24(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson24(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson24(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson24(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson25(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson25(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson25(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson25(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson25Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson25Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson25(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson26(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson26(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson26(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson26(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson26Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson26Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson26(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson27(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson27(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson27(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson27(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson27Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson27Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson27(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson28(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson28(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson28(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson28(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson28Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson28Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson28(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson29(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson29(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson29(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson29(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson29Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson29Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson29(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson30(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson30(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson30(ForgeGpuDemo *demo);
void ForgeGpuExportLesson30Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson30(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson31(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson31(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson31(ForgeGpuDemo *demo);
void ForgeGpuExportLesson31Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson31(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson32(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson32(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson32(ForgeGpuDemo *demo);
void ForgeGpuExportLesson32Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson32(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson33(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson33(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson33(ForgeGpuDemo *demo);
void ForgeGpuExportLesson33Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson33(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson34(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson34(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson34(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson34(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson34Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson34Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson34(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson35(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson35(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson35(ForgeGpuDemo *demo);
void ForgeGpuExportLesson35Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson35(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson36(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson36(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson36(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson36(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson36Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson36Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson36(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson37(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson37(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson37(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson37(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson37Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson37Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson37(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson38(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson38(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson38(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson38(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson38Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson38Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson38(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson39(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson39(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson39(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson39(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson39Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson39Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson39(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson40(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson40(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson40(ForgeGpuDemo *demo);
void ForgeGpuExportLesson40Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson40(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson41(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson41(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson41(ForgeGpuDemo *demo);
void ForgeGpuExportLesson41Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson41(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson42(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson42(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson42(ForgeGpuDemo *demo);
void ForgeGpuExportLesson42Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson42(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson43(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson43(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson43(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson43(ForgeGpuDemo *demo);
void ForgeGpuExportLesson43Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson43(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson44(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson44(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson44(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson44(ForgeGpuDemo *demo);
void ForgeGpuExportLesson44Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson44(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson45(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson45(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson45(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson45(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson45Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson45Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson45(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson46(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson46(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson46(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson46(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson46Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson46Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson46(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson47(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson47(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson47(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson47(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson47Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson47Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson47(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson48(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson48(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson48(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson48(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson48Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson48Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson48(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson49(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson49(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson49(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson49(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson49Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson49Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson49(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson50(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson50(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson50(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson50(ForgeGpuDemo *demo);
bool ForgeGpuHandleLesson50Event(ForgeGpuDemo *demo, const SDL_Event *event);
void ForgeGpuExportLesson50Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson50(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson51(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson51(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson51(ForgeGpuDemo *demo);
void ForgeGpuControlsLesson51(ForgeGpuDemo *demo);
void ForgeGpuExportLesson51Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson51(ForgeGpuDemo *demo);
bool ForgeGpuCreateLesson52(ForgeGpuDemo *demo);
bool ForgeGpuRenderLesson52(ForgeGpuDemo *demo, SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *swapchain_texture, Uint32 width, Uint32 height);
void ForgeGpuDebugLesson52(ForgeGpuDemo *demo);
void ForgeGpuExportLesson52Metrics(ForgeGpuDemo *demo);
void ForgeGpuDestroyLesson52(ForgeGpuDemo *demo);

#endif /* SDLGPU_FORGE_GPU_LESSONS_H */
