set(FORGE_GPU_SOURCES
    src/forge_gpu_demo.cpp
    src/forge_gpu_animation.cpp
    src/forge_gpu_assets.cpp
    src/forge_gpu_assets.h
    src/forge_gpu_browser_status.cpp
    src/forge_gpu_browser_status.h
    src/browser_status.h
    src/forge_gpu_camera.cpp
    src/forge_gpu_camera.h
    src/forge_gpu_deferred_scene.cpp
    src/forge_gpu_deferred_scene.h
    src/forge_gpu_forward_scene.cpp
    src/forge_gpu_forward_scene.h
    src/forge_gpu_gpu_helpers.cpp
    src/forge_gpu_gpu_helpers.h
    src/forge_gpu_imgui.cpp
    src/forge_gpu_imgui.h
    src/forge_gpu_internal.h
    src/forge_gpu_lesson_28_ui.c
    src/forge_gpu_lesson_28_ui.h
    src/forge_gpu_lesson_common.cpp
    src/forge_gpu_lesson_common.h
    src/forge_gpu_lessons.cpp
    src/forge_gpu_lessons.h
    src/forge_gpu_math.h
    src/forge_gpu_pipelines.cpp
    src/forge_gpu_pipelines.h
    src/forge_gpu_processed_assets.cpp
    src/forge_gpu_processed_assets.h
    src/forge_gpu_processed_scene_renderer.cpp
    src/forge_gpu_processed_scene_renderer.h
    src/forge_gpu_scene.cpp
    src/forge_gpu_scene.h
    src/forge_gpu_shapes.c
    src/forge_gpu_shapes.h
    src/lessons/forge_gpu_lesson_01_hello_window.cpp
    src/lessons/forge_gpu_lesson_02_first_triangle.cpp
    src/lessons/forge_gpu_lesson_03_uniforms_and_motion.cpp
    src/lessons/forge_gpu_lesson_04_textures_and_samplers.cpp
    src/lessons/forge_gpu_lesson_05_mipmaps.cpp
    src/lessons/forge_gpu_lesson_06_depth_and_3d.cpp
    src/lessons/forge_gpu_lesson_07_camera_and_input.cpp
    src/lessons/forge_gpu_lesson_08_mesh_loading.cpp
    src/lessons/forge_gpu_lesson_09_scene_loading.cpp
    src/lessons/forge_gpu_lesson_10_basic_lighting.cpp
    src/lessons/forge_gpu_lesson_11_compute_shaders.cpp
    src/lessons/forge_gpu_lesson_12_shader_grid.cpp
    src/lessons/forge_gpu_lesson_13_instanced_rendering.cpp
    src/lessons/forge_gpu_lesson_14_environment_mapping.cpp
    src/lessons/forge_gpu_lesson_15_cascaded_shadow_maps.cpp
    src/lessons/forge_gpu_lesson_16_blending.cpp
    src/lessons/forge_gpu_lesson_17_normal_maps.cpp
    src/lessons/forge_gpu_lesson_18_blinn_phong_materials.cpp
    src/lessons/forge_gpu_lesson_19_debug_lines.cpp
    src/lessons/forge_gpu_lesson_20_linear_fog.cpp
    src/lessons/forge_gpu_lesson_21_hdr_tone_mapping.cpp
    src/lessons/forge_gpu_lesson_22_bloom.cpp
    src/lessons/forge_gpu_lesson_23_point_light_shadows.cpp
    src/lessons/forge_gpu_lesson_24_gobo_spotlight.cpp
    src/lessons/forge_gpu_lesson_25_shader_noise.cpp
    src/lessons/forge_gpu_lesson_26_procedural_sky.cpp
    src/lessons/forge_gpu_lesson_27_ssao.cpp
    src/lessons/forge_gpu_lesson_28_ui_rendering.cpp
    src/lessons/forge_gpu_lesson_29_screen_space_reflections.cpp
    src/lessons/forge_gpu_lesson_30_planar_reflections.cpp
    src/lessons/forge_gpu_lesson_31_transform_animations.cpp
    src/lessons/forge_gpu_lesson_32_skinning_animations.cpp
    src/lessons/forge_gpu_lesson_33_vertex_pulling.cpp
    src/lessons/forge_gpu_lesson_34_stencil_testing.cpp
    src/lessons/forge_gpu_lesson_35_decals.cpp
    src/lessons/forge_gpu_lesson_36_edge_detection.cpp
    src/lessons/forge_gpu_lesson_37_3d_picking.cpp
    src/lessons/forge_gpu_lesson_38_indirect_drawing.cpp
    src/lessons/forge_gpu_lesson_39_pipeline_processed_assets.cpp
    src/lessons/forge_gpu_lesson_40_scene_renderer.cpp
    src/lessons/forge_gpu_lesson_41_scene_model_loading.cpp
    src/lessons/forge_gpu_lesson_42_pipeline_texture_compression.cpp
    src/lessons/forge_gpu_lesson_43_pipeline_skinned_animations.cpp
    src/lessons/forge_gpu_lesson_44_pipeline_morph_animations.cpp
    src/lessons/forge_gpu_lesson_45_scene_transparency_sorting.cpp
    src/lessons/forge_gpu_lesson_46_particle_animations.cpp
    src/lessons/forge_gpu_lesson_47_texture_atlas_rendering.cpp
    src/lessons/forge_gpu_lesson_48_height_map_terrain.cpp
    src/lessons/forge_gpu_lesson_49_imposters.cpp
    src/lessons/forge_gpu_lesson_50_grass_rendering.cpp
    src/lessons/forge_gpu_lesson_51_pbr_shading.cpp
    src/lessons/forge_gpu_lesson_52_pbr_textures.cpp
    third_party/cJSON/cJSON.c
    third_party/cJSON/cJSON.h
    third_party/imgui/imgui.cpp
    third_party/imgui/imgui_draw.cpp
    third_party/imgui/imgui_tables.cpp
    third_party/imgui/imgui_widgets.cpp
    third_party/imgui/backends/imgui_impl_sdl3.cpp
    third_party/imgui/backends/imgui_impl_sdlgpu3.cpp
)

set(FORGE_GPU_GENERATED_SHADER_HEADERS
    forge_gpu_lesson_02_shaders.h
    forge_gpu_lesson_03_shaders.h
    forge_gpu_lesson_04_shaders.h
    forge_gpu_lesson_05_shaders.h
    forge_gpu_lesson_06_shaders.h
    forge_gpu_lesson_07_shaders.h
    forge_gpu_lesson_08_shaders.h
    forge_gpu_lesson_09_shaders.h
    forge_gpu_lesson_10_shaders.h
    forge_gpu_lesson_11_shaders.h
    forge_gpu_lesson_12_shaders.h
    forge_gpu_lesson_13_shaders.h
    forge_gpu_lesson_14_shaders.h
    forge_gpu_lesson_15_shaders.h
    forge_gpu_lesson_16_shaders.h
    forge_gpu_lesson_17_shaders.h
    forge_gpu_lesson_18_shaders.h
    forge_gpu_lesson_19_shaders.h
    forge_gpu_lesson_20_shaders.h
    forge_gpu_lesson_21_shaders.h
    forge_gpu_lesson_22_shaders.h
    forge_gpu_lesson_23_shaders.h
    forge_gpu_lesson_24_shaders.h
    forge_gpu_lesson_25_shaders.h
    forge_gpu_lesson_26_shaders.h
    forge_gpu_lesson_27_shaders.h
    forge_gpu_lesson_28_shaders.h
    forge_gpu_lesson_29_shaders.h
    forge_gpu_lesson_30_shaders.h
    forge_gpu_lesson_31_shaders.h
    forge_gpu_lesson_32_shaders.h
    forge_gpu_lesson_33_shaders.h
    forge_gpu_lesson_34_shaders.h
    forge_gpu_lesson_35_shaders.h
    forge_gpu_lesson_36_shaders.h
    forge_gpu_lesson_37_shaders.h
    forge_gpu_lesson_38_shaders.h
    forge_gpu_lesson_39_shaders.h
    forge_gpu_lesson_40_shaders.h
    forge_gpu_lesson_46_shaders.h
    forge_gpu_lesson_49_shaders.h
    forge_gpu_lesson_50_shaders.h
    forge_gpu_lesson_51_shaders.h
    forge_gpu_lesson_52_shaders.h
    forge_gpu_shared_scene_shaders.h
)
